name: Deploy Dist

on:
  push:
    branches:
      - main
    paths-ignore:
      #- '.github/workflows/*'
      #- 'README.md'
  workflow_dispatch:
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore GradeSolution.sln

      - name: Test
        run: dotnet test GradeSolution.sln -c Release

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore GradeSolution.sln

      - name: Build
        run: dotnet build GradeSolution.sln -c Release --no-restore

      - name: Upload GradeSolution Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: GradeSolution-files
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
     
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
            token: ${{ secrets.GITHUB_TOKEN }}