name: Deploy to IIS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore GradeSolution.sln
      - run: dotnet test GradeSolution.sln -c Release


  build:
    needs: test
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore GradeSolution.sln
      - run: dotnet publish GradeSolution.sln -c Release -o publish

      - name: Zip Publish Folder
        run: Compress-Archive -Path publish\* -DestinationPath publish.zip

      - uses: actions/upload-artifact@v4
        with:
          name: app
          path: publish.zip


 deploy:
  needs: build
  runs-on: self-hosted

  steps:
    - uses: actions/download-artifact@v4
      with:
        name: app

    - name: Stop App Pool
      run: |
        Import-Module WebAdministration
        Stop-WebAppPool -Name "AppCICD"

    - name: Extract Files
      run: |
        Expand-Archive publish.zip -DestinationPath C:\SymphonySofttech\WebApp\Archive -Force

    - name: Copy Files
      run: |
        Copy-Item C:\SymphonySofttech\WebApp\Archive\* C:\SymphonySofttech\WebApp\AppCICD -Recurse -Force

    - name: Start App Pool
      run: |
        Start-WebAppPool -Name "AppCICD"
